name: A workflow for checking if an action is verified
on: push

jobs:
  verify-action:
    name: Verify action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Verify action
      - uses: ./github/actions/verified
        with:
          urlAction: "https://github.com/marketplace/actions/apppack-upload-artifacts"
